config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
    resources :informations, only: [:new, :create, :show]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  validates :number_of_letters, numericality: { less_than_or_equal_to: 15, only_integer: true }

  REPONSE = ["Oui", "Non"]
  LETTERS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
  LETTERS_OF_YEARS = {
    2020=> "R",
    2021=> "S",
    2022=> "T",
    2023=> "U",
    2024=> "V",
    2025=> "A",
    2026=> "B",
    2027=> "C",
    2028=> "D"
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def new
    @information = Information.new
    @year = Time.current.year
  end

  def create
    @information = Information.new(params_information)
    result(@information.letter_of_the_year, @information.number_of_letters, @information.unwanted_letters)
    if @information.save
      render(:show)
    else
      redirect_to new_path
    end
  end

  private

  def result(letter_of_the_year, number_of_letters, unwanted_letters)
    @year = Time.current.year
    @letters_name = Information::LETTERS.delete(unwanted_letters)
    if letter_of_the_year == false
      @name_lenght = Information::LETTERS.sample(number_of_letters)
      @result = @name_lenght.join
    elsif letter_of_the_year == true
      @first_letter_result = Information::LETTERS_OF_YEARS[@year]
      @name_lenght = Information::LETTERS.sample(number_of_letters - 1)
      @result = @first_letter_result + @name_lenght.join
    end
  end

  def params_information
    params.require(:information).permit(:letter_of_the_year, :number_of_letters, :unwanted_letters)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/informations/new.html.erb
<div class="page-container content">
  <div class="form-image">
    <img src="/assets/form-img.png" alt="" class="form-img">
  </div>
  <div class="d-flex flex-wrap justify-content-center">
    <div class="first-form m-3">
      <h1 class="text-center">Quelles sont tes préférences?</h1>
      <br>
      <%= simple_form_for @information, url: informations_path do |f| %>
        <%= f.input :letter_of_the_year, collection: Information::REPONSE, as: :radio_buttons, label: "Nous sommes en #{@year}, voudrais tu que le prénom de ton chien commence par la lettre #{Information::LETTERS_OF_YEARS[@year]}?" %>
        <%= f.input :unwanted_letters, as: :check_boxes, collection: Information::LETTERS, label: "Quelles lettres ne veux-tu pas?" %>
        <%= f.input :number_of_letters, as: :integer, label: "Combien de lettres veux-tu dans le nom?"%>
        <div class="text-center mb-3">
          <%= f.submit "Woof Woof!", class: "btn-submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/informations/show.html.erb
<%= @result %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home content">
    <div class="text-home pt-3">
      <p class="mb-2">Tu cherches un nom pour ton chien ?</p>
      <p class="mb-2">Trouves en un avec</p>
    </div>
    <%= link_to image_tag("/assets/woofwoof.png", class: 'button-logo'), new_information_path, class: "img-back" %>
    <div class="back-home"></div>
</div>